In [ ]:
import numpy as np

In [ ]:
# 스칼라
x = np.array([3.0])
y = np.array([2.0])
print(x.shape) # 배열의 크기
print('x + y = ', x+y)
print('x * y = ', x*y)

(1,)
x + y =  [5.]
x * y =  [6.]


In [ ]:
# 벡터
a = np.array([1,2, 3, 4, 5])
b = np.arange(4)
print(b)

[0 1 2 3]


In [ ]:
# 행렬
A = np.array([[1,2,3], [4, 5, 6]])
print(A)
A.shape # 두개 배열 3개 item

B = np.arange(20).reshape((5, 4))
print(B)
B.shape

[[1 2 3]
 [4 5 6]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


(5, 4)

In [ ]:
# 텐서
X = np.array([[[1, 2, 3], [4, 5, 6], [5, 6, 7]], [[1, 3, 4], [2, 3, 4], [6, 7, 8]]])
print(X)
X.shape

Y = np.arange(24).reshape((2, 3, 4))
print('Y.shape = ', Y.shape)
print('Y =', Y)

[[[1 2 3]
  [4 5 6]
  [5 6 7]]

 [[1 3 4]
  [2 3 4]
  [6 7 8]]]
Y.shape =  (2, 3, 4)
Y = [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
# zeros(), eye(), ones() function
np.zeros((3, 4))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
# 브로드캐스팅
a = np.array([10, 11, 12])
print(a-10)

[0 1 2]


In [ ]:
A = np.array([[10, 20, 30], [14, 15, 16]])
print(A.shape)

print(A-a)


(2, 3)
[[ 0  9 18]
 [ 4  4  4]]


In [ ]:
# 벡터와 벡터의 곱셈 
x = np.array([1,2,3])
y =np.array([4, 5,6])

print(np.dot(x, y)) # 벡터 내적 dot
print(x@y) 

32
32


In [ ]:
# 행렬과 행렬의 곱셈
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
print(A.shape)
print(B.shape)
print(A@B)

(2, 3)
(3, 2)
[[22 28]
 [49 64]]


In [ ]:
# 놈(Norm)
x = np.array([[1],[2],[3]])
L1_norm = np.linalg.norm(x, ord=1)
print(L1_norm)

L2_norm = np.linalg.norm(x, ord=2) # 제곱의 합 -> 제곱근
print(L2_norm)

6.0
3.7416573867739413
